export const CONSTANTS = {
  DEFAULT_DATE_FORMAT: 'YYYY-MM-DD',
  DEFAULT_WEEK_DATE_FORMAT: 'GGGG-[W]WW',
  DEFAULT_MONTH_DATE_FORMAT: 'YYYY-MM',
  DEFAULT_QUARTER_DATE_FORMAT: 'YYYY-[Q]Q',
  DEFAULT_YEAR_DATE_FORMAT: 'YYYY',
  TODO_CALLOUT_REGEX: /^> \[!EXAMPLE\] .* <js-todo-callout><\/js-todo-callout>$/gm,
  FRONTMATTER_REGEX: /^---\s*\n([\s\S]*?\n)---/m,
  GOALS_FOLDER: '0-plan/0-goals',
  DAILY_FOLDER: '0-plan/1-daily',
  WEEKLY_FOLDER: '0-plan/2-weekly',
  MONTHLY_FOLDER: '0-plan/3-monthly',
  QUARTERLY_FOLDER: '0-plan/4-quarterly',
  YEARLY_FOLDER: '0-plan/5-yearly',
  PROJECTS_FOLDER: '1-projects',
  AREAS_FOLDER: '2-areas',
  RESOURCES_FOLDER: '3-resources',
  ARCHIVES_FOLDER: '4-archives',
  NOTES_FOLDER: '5-notes',
  SOMEDAY_FILE_PATH: 'Someday-Maybe.md',
  TEMPLATES: {
    DAILY: 'templates/plan/Daily.md',
    WEEKLY: 'templates/plan/Weekly.md',
    MONTHLY: 'templates/plan/Monthly.md',
    QUARTERLY: 'templates/plan/Quarterly.md',
    YEARLY: 'templates/plan/Yearly.md',
    FLEETING_NOTE: 'templates/notes/Fleeting.md',
    GOAL: 'templates/plan/Goal.md',
    PROJECT: 'templates/para/Project.md',
    AREA: 'templates/para/Area.md',
    RESOURCE: 'templates/para/Resource.md',
  },
}
