export declare const VALUE_SYNTAX = "{{value}}";
export declare const DATE_SYNTAX = "{{date}}";
export declare const TIME_SYNTAX = "{{time}}";
export declare const NAME_SYNTAX = "{{name}}";
export declare const VARIABLE_SYNTAX = "{{value:<variable name>}}";
export declare const FIELD_VAR_SYNTAX = "{{field:<field name>}}";
export declare const MATH_VALUE_SYNTAX = "{{mvalue}}";
export declare const LINKCURRENT_SYNTAX = "{{linkcurrent}}";
export declare const TITLE_SYNTAX = "{{title}}";
export declare const SELECTED_SYNTAX = "{{selected}}";
export declare const FORMAT_SYNTAX: string[];
export declare const FILE_NAME_FORMAT_SYNTAX: string[];
export declare const TEMPLATE_FORMAT_SYNTAX: string[];
export declare const FILE_NUMBER_REGEX: RegExp;
export declare const NUMBER_REGEX: RegExp;
export declare const CREATE_IF_NOT_FOUND_TOP = "top";
export declare const CREATE_IF_NOT_FOUND_BOTTOM = "bottom";
export declare const DATE_REGEX: RegExp;
export declare const DATE_REGEX_FORMATTED: RegExp;
export declare const TIME_REGEX: RegExp;
export declare const TIME_REGEX_FORMATTED: RegExp;
export declare const NAME_VALUE_REGEX: RegExp;
export declare const VARIABLE_REGEX: RegExp;
export declare const FIELD_VAR_REGEX: RegExp;
export declare const DATE_VARIABLE_REGEX: RegExp;
export declare const LINK_TO_CURRENT_FILE_REGEX: RegExp;
export declare const MARKDOWN_FILE_EXTENSION_REGEX: RegExp;
export declare const JAVASCRIPT_FILE_EXTENSION_REGEX: RegExp;
export declare const MACRO_REGEX: RegExp;
export declare const TEMPLATE_REGEX: RegExp;
export declare const LINEBREAK_REGEX: RegExp;
export declare const INLINE_JAVASCRIPT_REGEX: RegExp;
export declare const MATH_VALUE_REGEX: RegExp;
export declare const TITLE_REGEX: RegExp;
export declare const SELECTED_REGEX: RegExp;
export declare const FILE_LINK_REGEX: RegExp;
export declare const TAG_REGEX: RegExp;
export declare const DATE_SYNTAX_SUGGEST_REGEX: RegExp;
export declare const DATE_FORMAT_SYNTAX_SUGGEST_REGEX: RegExp;
export declare const NAME_SYNTAX_SUGGEST_REGEX: RegExp;
export declare const VALUE_SYNTAX_SUGGEST_REGEX: RegExp;
export declare const VARIABLE_SYNTAX_SUGGEST_REGEX: RegExp;
export declare const VARIABLE_DATE_SYNTAX_SUGGEST_REGEX: RegExp;
export declare const LINKCURRENT_SYNTAX_SUGGEST_REGEX: RegExp;
export declare const TEMPLATE_SYNTAX_SUGGEST_REGEX: RegExp;
export declare const MACRO_SYNTAX_SUGGEST_REGEX: RegExp;
export declare const MATH_VALUE_SYNTAX_SUGGEST_REGEX: RegExp;
export declare const TITLE_SYNTAX_SUGGEST_REGEX: RegExp;
export declare const SELECTED_SYNTAX_SUGGEST_REGEX: RegExp;
export declare const TIME_SYNTAX_SUGGEST_REGEX: RegExp;
export declare const TIME_FORMAT_SYNTAX_SUGGEST_REGEX: RegExp;
export declare const fileExistsIncrement: "Increment the file name";
export declare const fileExistsAppendToBottom: "Append to the bottom of the file";
export declare const fileExistsAppendToTop: "Append to the top of the file";
export declare const fileExistsOverwriteFile: "Overwrite the file";
export declare const fileExistsDoNothing: "Nothing";
export declare const fileExistsChoices: readonly ["Append to the bottom of the file", "Append to the top of the file", "Overwrite the file", "Increment the file name", "Nothing"];
export declare const WIKI_LINK_REGEX: RegExp;
